project:
  type: website
  output-dir: docs

website:
  title: "azumaya"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    code-tools: true
    theme: zephyr
    css: styles.css
    toc: true
    lang: ja