project:
  type: website
  output-dir: docs
  render: 
    - "/posts/*"
    - "*.qmd"

website:
  title: "azumaya"
  navbar:
    left:
      - about.qmd
      - posts.qmd
    right:
      - icon: github
        href: https://github.com/azumaya2126
      - icon: twitter
        href: https://twitter.com/azumaya2126
  page-footer: 
    center: 
      - text: "© 2024, azumaya"
        href: terms.qmd

format:
  html:
    theme: Zephyr
    css: styles.css
    lang: ja
    link-external-newwindow: true
    
