project:
  type: website
  output-dir: docs

website:
  title: "azumaya web"
  navbar:
    left:
      - about.qmd
      - posts.qmd
    right:
      - icon: github
        href: https://github.com/azumaya2126
      - icon: twitter
        href: https://twitter.com/18azumaya

format:
  html:
    theme: Zephyr
    css: styles.css
    lang: ja
    link-external-newwindow: true
