project:
  type: website
  output-dir: docs

website:
  title: "azumaya"
  navbar:
    left:
      - about.qmd
      - post.qmd

format:
  html:
    theme: Zephyr
    css: styles.css
    toc: true
    lang: ja
    link-external-newwindow: TRUE